Sum function is throwing an error! Determine why the error is thrown, and handle it using try...catch and print the error by using custom handleError function


Create sayName(name) function that will print the name that is passed to it if name argument is a string. It should throw a TypeError if name is not a string.

Run sayName function inside of try...catch and print out error message if error is thrown. 


Create a custom ValidationError class that extends Error class. Throw a ValidationError with a message.